name = "iknowmyip"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build:client"
cwd = "."
watch_dir = ["src", "client"]

[env.production]
name = "iknowmyip"

[env.dev]
name = "iknowmyip-dev"

# Variables
[vars]
ENVIRONMENT = "production"

# Static assets
[assets]
directory = "dist"
binding = "ASSETS"