name = "iknowmyip"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[env.production]
name = "iknowmyip"

[env.dev]
name = "iknowmyip-dev"

# Variables
[vars]
ENVIRONMENT = "production"

# Static assets handled by worker code instead of assets binding

# Static assets configuration
[site]
bucket = "./dist"