name = "iknowmyip"
main = "src/worker.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "iknowmyip"

[env.dev]
name = "iknowmyip-dev"

# Variables
[vars]
ENVIRONMENT = "production"

# Static assets
[assets]
directory = "dist/static"
binding = "ASSETS"